/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountManagement: typeof import('./components/AccountManagement.vue')['default']
    AdminDashboard: typeof import('./components/admin/AdminDashboard.vue')['default']
    AdminInlineTools: typeof import('./components/admin/AdminInlineTools.vue')['default']
    CommentPanel: typeof import('./components/posts/CommentPanel.vue')['default']
    PostCard: typeof import('./components/posts/PostCard.vue')['default']
    PostFeed: typeof import('./components/posts/PostFeed.vue')['default']
    PostPreviewPanel: typeof import('./components/posts/PostPreviewPanel.vue')['default']
    ResolvedImage: typeof import('./components/ResolvedImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoryArcCards: typeof import('./components/StoryArcCards.vue')['default']
    TheCharacters: typeof import('./components/TheCharacters.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TitlePlate: typeof import('./components/TitlePlate.vue')['default']
    WelcomeSection: typeof import('./components/WelcomeSection.vue')['default']
    WorldEntryCards: typeof import('./components/WorldEntryCards.vue')['default']
  }
}
