/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountManagement: typeof import('./components/AccountManagement.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideAdvertisement: typeof import('./components/SideAdvertisement.vue')['default']
    TheCharacters: typeof import('./components/TheCharacters.vue')['default']
    TheComics: typeof import('./components/TheComics.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TitlePlate: typeof import('./components/TitlePlate.vue')['default']
    WelcomeSection: typeof import('./components/WelcomeSection.vue')['default']
  }
}
